name: flutter_map_example
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  flutter_map:
    path: ../flutter_map

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/offlineMap/12/2177/
    - assets/offlineMap/12/2178/
    - assets/offlineMap/12/2179/
    - assets/offlineMap/12/2180/
    - assets/offlineMap/12/2181/
    - assets/offlineMap/13/4354/
    - assets/offlineMap/13/4355/
    - assets/offlineMap/13/4356/
    - assets/offlineMap/13/4357/
    - assets/offlineMap/13/4358/
    - assets/offlineMap/13/4359/
    - assets/offlineMap/13/4360/
    - assets/offlineMap/13/4361/
    - assets/offlineMap/13/4362/
    - assets/offlineMap/13/4363/
    - assets/offlineMap/14/8709/
    - assets/offlineMap/14/8710/
    - assets/offlineMap/14/8711/
    - assets/offlineMap/14/8712/
    - assets/offlineMap/14/8713/
    - assets/offlineMap/14/8714/
    - assets/offlineMap/14/8715/
    - assets/offlineMap/14/8716/
    - assets/offlineMap/14/8717/
    - assets/offlineMap/14/8718/
    - assets/offlineMap/14/8719/
    - assets/offlineMap/14/8720/
    - assets/offlineMap/14/8721/
    - assets/offlineMap/14/8722/
    - assets/offlineMap/14/8723/
    - assets/offlineMap/14/8724/
    - assets/offlineMap/14/8725/
    - assets/offlineMap/14/8726/
    - assets/offlineMap/14/8727/
    - assets/offlineMap/15/17419/
    - assets/offlineMap/15/17420/
    - assets/offlineMap/15/17421/
    - assets/offlineMap/15/17422/
    - assets/offlineMap/15/17423/
    - assets/offlineMap/15/17424/
    - assets/offlineMap/15/17425/
    - assets/offlineMap/15/17426/
    - assets/offlineMap/15/17427/
    - assets/offlineMap/15/17428/
    - assets/offlineMap/15/17429/
    - assets/offlineMap/15/17430/
    - assets/offlineMap/15/17431/
    - assets/offlineMap/15/17432/
    - assets/offlineMap/15/17433/
    - assets/offlineMap/15/17434/
    - assets/offlineMap/15/17435/
    - assets/offlineMap/15/17436/
    - assets/offlineMap/15/17437/
    - assets/offlineMap/15/17438/
    - assets/offlineMap/15/17439/
    - assets/offlineMap/15/17440/
    - assets/offlineMap/15/17441/
    - assets/offlineMap/15/17442/
    - assets/offlineMap/15/17443/
    - assets/offlineMap/15/17444/
    - assets/offlineMap/15/17445/
    - assets/offlineMap/15/17446/
    - assets/offlineMap/15/17447/
    - assets/offlineMap/15/17448/
    - assets/offlineMap/15/17449/
    - assets/offlineMap/15/17450/
    - assets/offlineMap/15/17451/
    - assets/offlineMap/15/17452/
    - assets/offlineMap/15/17453/
    - assets/offlineMap/15/17454/
    - assets/offlineMap/15/17455/
    - assets/offlineMap/16/34839/
    - assets/offlineMap/16/34840/
    - assets/offlineMap/16/34841/
    - assets/offlineMap/16/34842/
    - assets/offlineMap/16/34843/
    - assets/offlineMap/16/34844/
    - assets/offlineMap/16/34845/
    - assets/offlineMap/16/34846/
    - assets/offlineMap/16/34847/
    - assets/offlineMap/16/34848/
    - assets/offlineMap/16/34849/
    - assets/offlineMap/16/34850/
    - assets/offlineMap/16/34851/
    - assets/offlineMap/16/34852/
    - assets/offlineMap/16/34853/
    - assets/offlineMap/16/34854/
    - assets/offlineMap/16/34855/
    - assets/offlineMap/16/34856/
    - assets/offlineMap/16/34857/
    - assets/offlineMap/16/34858/
    - assets/offlineMap/16/34859/
    - assets/offlineMap/16/34860/
    - assets/offlineMap/16/34861/
    - assets/offlineMap/16/34862/
    - assets/offlineMap/16/34863/
    - assets/offlineMap/16/34864/
    - assets/offlineMap/16/34865/
    - assets/offlineMap/16/34866/
    - assets/offlineMap/16/34867/
    - assets/offlineMap/16/34868/
    - assets/offlineMap/16/34869/
    - assets/offlineMap/16/34872/
    - assets/offlineMap/16/34873/
    - assets/offlineMap/16/34874/
    - assets/offlineMap/16/34875/
    - assets/offlineMap/16/34870/
    - assets/offlineMap/16/34871/
    - assets/offlineMap/16/34876/
    - assets/offlineMap/16/34877/
    - assets/offlineMap/16/34880/
    - assets/offlineMap/16/34881/
    - assets/offlineMap/16/34878/
    - assets/offlineMap/16/34879/
    - assets/offlineMap/16/34884/
    - assets/offlineMap/16/34885/
    - assets/offlineMap/16/34882/
    - assets/offlineMap/16/34883/
    - assets/offlineMap/16/34892/
    - assets/offlineMap/16/34893/
    - assets/offlineMap/16/34886/
    - assets/offlineMap/16/34887/
    - assets/offlineMap/16/34888/
    - assets/offlineMap/16/34889/
    - assets/offlineMap/16/34890/
    - assets/offlineMap/16/34891/
    - assets/offlineMap/16/34894/
    - assets/offlineMap/16/34895/
    - assets/offlineMap/16/34898/
    - assets/offlineMap/16/34899/
    - assets/offlineMap/16/34896/
    - assets/offlineMap/16/34897/
    - assets/offlineMap/16/34900/
    - assets/offlineMap/16/34901/
    - assets/offlineMap/16/34902/
    - assets/offlineMap/16/34903/
    - assets/offlineMap/16/34906/
    - assets/offlineMap/16/34907/
    - assets/offlineMap/16/34904/
    - assets/offlineMap/16/34905/
    - assets/offlineMap/16/34908/
    - assets/offlineMap/16/34909/
    - assets/offlineMap/16/34910/
    - assets/offlineMap/16/34911/